<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD3gpuap\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD3gpuap/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerD3gpuap.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerD3gpuap\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerD3gpuap\appDevDebugProjectContainer([
    'container.build_hash' => 'D3gpuap',
    'container.build_id' => '0ed94109',
    'container.build_time' => 1590649031,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD3gpuap');
